export {default as lawMessage} from './law-message';
export {default as locationMessage} from './location-message';
export {default as loginMessage} from './login-form-message';
export {default as lowsAdminFormMessage} from './lows-admin-form-message';
export {default as registerAssetsMessage} from './registerAssetsMessage';
export {default as registerUserMessage} from './registerUser-form-message';
export {default as transferAdminFormMessage} from './transfer-admin-form-message';
export {default as UserEditMessage} from './user-edit-message';
export {default as editUsersMessage} from './user-message';
